export const locales = [
  { id: "en", label: "English", privacy: "PRIVACY.en.md", locale: "en-US" },
  { id: "zh-Hans", label: "简体中文", privacy: "PRIVACY.md", locale: "zh-CN" },
  { id: "zh-Hant", label: "繁體中文", privacy: "PRIVACY.zh-Hant.md", locale: "zh-TW" },
  { id: "ja", label: "日本語", privacy: "PRIVACY.ja.md", locale: "ja-JP" },
  { id: "ko", label: "한국어", privacy: "PRIVACY.ko.md", locale: "ko-KR" },
  { id: "es", label: "Español", privacy: "PRIVACY.es.md", locale: "es-ES" },
  { id: "fr", label: "Français", privacy: "PRIVACY.fr.md", locale: "fr-FR" },
  { id: "de", label: "Deutsch", privacy: "PRIVACY.de.md", locale: "de-DE" }
];

export const copy = {
  en: {
    support: "Support", privacy: "Privacy", switchLanguage: "Language", home: "Home",
    title: "Your contacts stay on your device.",
    intro: "ContactsDeduper finds duplicate contacts on your iPhone or Mac, so you can review and merge them carefully. Create a backup before changes, and restore anytime.",
    getSupport: "Get support", readPrivacy: "Read the privacy policy", whatItDoes: "What it does",
    whatItDoesText: "Finds duplicate contacts, including same name, phone, email, and more. You review each group and decide what to merge.",
    careful: "Built for careful cleanup", carefulText: "Preview every duplicate set before merging. Choose which details to keep, and see the result before you confirm.",
    backup: "Backup and restore", backupText: "Create a full backup of your contacts before you make changes. Restore anytime if you need to.",
    questions: "Questions & answers", faq: [
      ["Does ContactsDeduper upload my contacts?", "No. Your contacts are processed locally and are never uploaded to us."],
      ["Is it safe to merge contacts?", "You can preview every duplicate set and choose exactly what to keep. Export a backup before changes."],
      ["Can I restore my contacts?", "Yes. Restore from a backup you created with ContactsDeduper."],
      ["Which devices and versions are supported?", "ContactsDeduper supports iOS 17 or later and native macOS 14 or later."]
    ],
    feedback: "For help, use GitHub Issues. Do not attach real contact data or backup files.",
    github: "GitHub", updated: "Last updated"
  },
  "zh-Hans": {
    support: "支持", privacy: "隐私", switchLanguage: "语言", home: "首页",
    title: "你的联系人始终留在设备上。", intro: "ContactsDeduper 在 iPhone 或 Mac 上查找重复联系人，让你谨慎地检查和合并。修改前先创建备份，之后也可随时恢复。", getSupport: "获取支持", readPrivacy: "查看隐私政策", whatItDoes: "它能做什么", whatItDoesText: "查找姓名、电话、邮箱等重复联系人。你可以逐组检查并决定要合并哪些联系人。", careful: "为谨慎清理而设计", carefulText: "合并前预览每组重复联系人，选择要保留的资料，并在确认前查看结果。", backup: "备份与恢复", backupText: "修改前创建完整通讯录备份，需要时可以随时恢复。", questions: "常见问题", faq: [["ContactsDeduper 会上传我的联系人吗？", "不会。联系人只在本地处理，不会上传给我们。"], ["合并联系人安全吗？", "你可以预览每组重复联系人，并明确选择要保留的内容。修改前建议导出备份。"], ["可以恢复联系人吗？", "可以，从 ContactsDeduper 创建的备份中恢复。"], ["支持哪些设备和系统版本？", "支持 iOS 17 或更高版本，以及原生 macOS 14 或更高版本。"]], feedback: "如需帮助，请通过 GitHub Issues 联系。请勿附加真实联系人数据或备份文件。", github: "GitHub", updated: "最后更新"
  },
  "zh-Hant": {
    support: "支援", privacy: "私隱", switchLanguage: "語言", home: "首頁", title: "你的聯絡人始終留在裝置上。", intro: "ContactsDeduper 在 iPhone 或 Mac 上尋找重複聯絡人，讓你仔細檢查及合併。修改前先建立備份，之後也可隨時還原。", getSupport: "取得支援", readPrivacy: "查看私隱政策", whatItDoes: "功能介紹", whatItDoesText: "尋找姓名、電話、電子郵件等重複聯絡人。你可以逐組檢查並決定要合併哪些聯絡人。", careful: "為仔細整理而設", carefulText: "合併前預覽每組重複聯絡人，選擇要保留的資料，並在確認前查看結果。", backup: "備份與還原", backupText: "修改前建立完整通訊錄備份，需要時可以隨時還原。", questions: "常見問題", faq: [["ContactsDeduper 會上傳我的聯絡人嗎？", "不會。聯絡人只在本機處理，不會上傳給我們。"], ["合併聯絡人安全嗎？", "你可以預覽每組重複聯絡人，並明確選擇要保留的內容。修改前建議匯出備份。"], ["可以還原聯絡人嗎？", "可以，從 ContactsDeduper 建立的備份中還原。"], ["支援哪些裝置和系統版本？", "支援 iOS 17 或以上版本，以及原生 macOS 14 或以上版本。"]], feedback: "如需協助，請透過 GitHub Issues 聯絡。請勿附加真實聯絡人資料或備份檔案。", github: "GitHub", updated: "最後更新"
  }
};

const fallback = copy.en;
for (const locale of locales) {
  copy[locale.id] ??= { ...fallback, ...copy.en, title: `${fallback.title}` };
}

Object.assign(copy.ja, { support: "サポート", privacy: "プライバシー", switchLanguage: "言語", home: "ホーム", title: "連絡先はデバイスに残ります。", intro: "ContactsDeduper は iPhone または Mac 上で重複する連絡先を見つけ、確認してから安全に統合できます。変更前にバックアップを作成し、いつでも復元できます。", getSupport: "サポートを見る", readPrivacy: "プライバシーポリシー", whatItDoes: "できること", whatItDoesText: "名前、電話番号、メールアドレスなどが重複する連絡先を見つけます。グループごとに確認して統合を選べます。", careful: "慎重な整理のために", carefulText: "統合前に重複セットをプレビューし、残す情報を選択して結果を確認できます。", backup: "バックアップと復元", backupText: "変更前に連絡先をバックアップできます。必要なときはいつでも復元できます。", questions: "よくある質問", faq: [["連絡先はアップロードされますか？", "いいえ。連絡先はデバイス上で処理され、私たちにアップロードされません。"], ["連絡先の統合は安全ですか？", "重複セットを確認し、残す内容を選択できます。変更前にバックアップを作成してください。"], ["連絡先を復元できますか？", "はい。ContactsDeduper で作成したバックアップから復元できます。"], ["対応する OS は？", "iOS 17 以降とネイティブ macOS 14 以降に対応しています。"]], feedback: "サポートが必要な場合は GitHub Issues を利用してください。実際の連絡先データやバックアップを添付しないでください。", github: "GitHub", updated: "最終更新" });
Object.assign(copy.ko, { support: "지원", privacy: "개인정보 보호", switchLanguage: "언어", home: "홈", title: "연락처는 기기에 남아 있습니다.", intro: "ContactsDeduper는 iPhone 또는 Mac에서 중복 연락처를 찾아 확인한 뒤 안전하게 병합합니다. 변경 전에 백업을 만들고 언제든 복원할 수 있습니다.", getSupport: "지원 받기", readPrivacy: "개인정보 처리방침", whatItDoes: "주요 기능", whatItDoesText: "이름, 전화번호, 이메일 등 중복 연락처를 찾습니다. 각 그룹을 검토하고 병합할 항목을 선택하세요.", careful: "신중한 정리를 위해", carefulText: "병합 전에 중복 그룹을 미리 보고 유지할 정보를 선택한 뒤 결과를 확인할 수 있습니다.", backup: "백업 및 복원", backupText: "변경 전에 연락처 전체를 백업하세요. 필요할 때 언제든 복원할 수 있습니다.", questions: "자주 묻는 질문", faq: [["연락처가 업로드되나요?", "아니요. 연락처는 기기에서 처리되며 어디에도 업로드되지 않습니다."], ["연락처 병합은 안전한가요?", "모든 중복 그룹을 미리 보고 유지할 내용을 선택할 수 있습니다. 변경 전에 백업하세요."], ["연락처를 복원할 수 있나요?", "예. ContactsDeduper에서 만든 백업으로 복원할 수 있습니다."], ["지원하는 OS는 무엇인가요?", "iOS 17 이상 및 네이티브 macOS 14 이상을 지원합니다."]], feedback: "도움이 필요하면 GitHub Issues를 이용하세요. 실제 연락처 데이터나 백업 파일을 첨부하지 마세요.", github: "GitHub", updated: "최근 업데이트" });
Object.assign(copy.es, { support: "Soporte", privacy: "Privacidad", switchLanguage: "Idioma", home: "Inicio", title: "Tus contactos permanecen en tu dispositivo.", intro: "ContactsDeduper encuentra contactos duplicados en tu iPhone o Mac para que puedas revisarlos y combinarlos con cuidado. Crea una copia antes de cambiar nada y restaura cuando quieras.", getSupport: "Obtener soporte", readPrivacy: "Leer la política de privacidad", whatItDoes: "Qué hace", whatItDoesText: "Encuentra contactos duplicados por nombre, teléfono, correo y más. Revisa cada grupo y decide qué combinar.", careful: "Limpieza cuidadosa", carefulText: "Previsualiza cada grupo duplicado antes de combinarlo. Elige qué datos conservar y revisa el resultado.", backup: "Copias y restauración", backupText: "Crea una copia completa antes de hacer cambios y restáurala cuando lo necesites.", questions: "Preguntas frecuentes", faq: [["¿ContactsDeduper sube mis contactos?", "No. Los contactos se procesan localmente y nunca se suben."], ["¿Es seguro combinar contactos?", "Puedes previsualizar cada grupo y elegir exactamente qué conservar. Haz una copia antes de cambiar nada."], ["¿Puedo restaurar mis contactos?", "Sí. Restaura una copia creada con ContactsDeduper."], ["¿Qué sistemas son compatibles?", "Compatible con iOS 17 o posterior y macOS nativo 14 o posterior."]], feedback: "Para obtener ayuda, usa GitHub Issues. No adjuntes datos reales de contactos ni copias de seguridad.", github: "GitHub", updated: "Última actualización" });
Object.assign(copy.fr, { support: "Assistance", privacy: "Confidentialité", switchLanguage: "Langue", home: "Accueil", title: "Vos contacts restent sur votre appareil.", intro: "ContactsDeduper trouve les contacts en double sur votre iPhone ou Mac pour vous permettre de les vérifier et de les fusionner avec soin. Créez une sauvegarde avant toute modification et restaurez-la à tout moment.", getSupport: "Obtenir de l’aide", readPrivacy: "Lire la politique de confidentialité", whatItDoes: "Fonctionnement", whatItDoesText: "Trouve les doublons par nom, téléphone, e-mail et plus encore. Vérifiez chaque groupe et décidez quoi fusionner.", careful: "Un nettoyage maîtrisé", carefulText: "Prévisualisez chaque groupe avant la fusion. Choisissez les informations à conserver et vérifiez le résultat.", backup: "Sauvegarde et restauration", backupText: "Créez une sauvegarde complète avant toute modification et restaurez-la si nécessaire.", questions: "Questions fréquentes", faq: [["ContactsDeduper téléverse-t-il mes contacts ?", "Non. Les contacts sont traités localement et ne sont jamais téléversés."], ["La fusion est-elle sûre ?", "Vous pouvez prévisualiser chaque groupe et choisir précisément ce qui est conservé. Faites une sauvegarde avant toute modification."], ["Puis-je restaurer mes contacts ?", "Oui. Restaurez une sauvegarde créée avec ContactsDeduper."], ["Quels systèmes sont pris en charge ?", "iOS 17 ou version ultérieure et macOS natif 14 ou version ultérieure."]], feedback: "Pour obtenir de l’aide, utilisez GitHub Issues. N’ajoutez pas de données de contacts réelles ni de sauvegardes.", github: "GitHub", updated: "Dernière mise à jour" });
Object.assign(copy.de, { support: "Support", privacy: "Datenschutz", switchLanguage: "Sprache", home: "Startseite", title: "Deine Kontakte bleiben auf deinem Gerät.", intro: "ContactsDeduper findet doppelte Kontakte auf deinem iPhone oder Mac, damit du sie sorgfältig prüfen und zusammenführen kannst. Erstelle vor Änderungen ein Backup und stelle es jederzeit wieder her.", getSupport: "Support erhalten", readPrivacy: "Datenschutzerklärung lesen", whatItDoes: "Das kann die App", whatItDoesText: "Findet doppelte Kontakte nach Name, Telefonnummer, E-Mail und mehr. Prüfe jede Gruppe und entscheide, was zusammengeführt wird.", careful: "Sorgfältig aufräumen", carefulText: "Sieh jede doppelte Gruppe vor dem Zusammenführen in der Vorschau an. Wähle die zu behaltenden Daten und prüfe das Ergebnis.", backup: "Backup und Wiederherstellung", backupText: "Erstelle vor Änderungen ein vollständiges Backup und stelle es bei Bedarf wieder her.", questions: "Häufige Fragen", faq: [["Werden meine Kontakte hochgeladen?", "Nein. Kontakte werden lokal verarbeitet und nie hochgeladen."], ["Ist das Zusammenführen sicher?", "Du kannst jede Gruppe in der Vorschau prüfen und genau auswählen, was bleibt. Erstelle vorher ein Backup."], ["Kann ich Kontakte wiederherstellen?", "Ja. Stelle ein mit ContactsDeduper erstelltes Backup wieder her."], ["Welche Systeme werden unterstützt?", "iOS 17 oder neuer sowie natives macOS 14 oder neuer."]], feedback: "Für Hilfe nutze GitHub Issues. Hänge keine echten Kontaktdaten oder Backup-Dateien an.", github: "GitHub", updated: "Zuletzt aktualisiert" });
