import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { siteURL, locales, copy } from "../src/site-data.mjs";
import { header, footer, markdownToHTML, escapeHTML } from "../src/site.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const website = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dist = path.join(website, "dist");
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
fs.copyFileSync(path.join(website, "src/styles.css"), path.join(dist, "styles.css"));
fs.copyFileSync(path.join(website, "public/favicon.svg"), path.join(dist, "favicon.svg"));
fs.copyFileSync(path.join(website, "public/_headers"), path.join(dist, "_headers"));

function shell({ locale, page, title, description, content }) {
  const labels = copy[locale.id];
  const alternates = locales.map((entry) => `<link rel="alternate" hreflang="${entry.locale}" href="${siteURL}/${entry.id}/${page}/">`).join("\n    ");
  return `<!doctype html><html lang="${locale.locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escapeHTML(description)}"><meta name="theme-color" content="#ffffff"><title>${escapeHTML(title)} · ContactsDeduper</title><link rel="canonical" href="${siteURL}/${locale.id}/${page}/">${alternates}<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"></head><body>${header({ locale, current: locale.id, page, locales, labels })}<main>${content}</main>${footer({ locale, labels })}</body></html>`;
}

for (const locale of locales) {
  const labels = copy[locale.id];
  const supportContent = `<section class="hero"><div><h1>${labels.title}</h1><p>${labels.intro}</p><div class="actions"><a class="button" href="https://github.com/gewill/ContactsDeduper/issues">${labels.getSupport}</a><a class="text-link" href="/${locale.id}/privacy/">${labels.readPrivacy} &nbsp;→</a></div></div><div class="phone-frame" aria-label="ContactsDeduper app preview"><div class="phone-screen"><div class="phone-notch"></div><h2>ContactsDeduper</h2><div class="status-row"><span>◯ Duplicate sets</span><strong>12</strong></div><div class="status-row"><span>♧ Duplicates found</span><strong>48</strong></div><div class="status-row"><span>♙ Contacts</span><strong>1,248</strong></div><a class="phone-button" href="https://github.com/gewill/ContactsDeduper/issues">Review duplicates</a><a class="phone-button secondary" href="/${locale.id}/privacy/">Backup now</a><p class="phone-foot">▣ Everything stays on your device.<br>No data is uploaded.</p></div></div></section><section class="feature-band"><div class="features"><article class="feature"><div class="feature-icon" aria-hidden="true">⌕</div><h2>${labels.whatItDoes}</h2><p>${labels.whatItDoesText}</p></article><article class="feature"><div class="feature-icon" aria-hidden="true">♢</div><h2>${labels.careful}</h2><p>${labels.carefulText}</p></article><article class="feature"><div class="feature-icon" aria-hidden="true">⌁</div><h2>${labels.backup}</h2><p>${labels.backupText}</p></article></div></section><section class="faq"><h2>${labels.questions}</h2>${labels.faq.map(([question, answer]) => `<details><summary>${question}</summary><p>${answer}</p></details>`).join("")}</section>`;
  write(path.join(dist, locale.id, "support", "index.html"), shell({ locale, page: "support", title: labels.support, description: labels.intro, content: supportContent }));
  write(path.join(dist, locale.id, "index.html"), `<!doctype html><html lang="${locale.locale}"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=/${locale.id}/support/"><link rel="canonical" href="/${locale.id}/support/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><title>ContactsDeduper</title></head><body><p><a href="/${locale.id}/support/">${labels.support}</a></p></body></html>`);
  const privacy = fs.readFileSync(path.join(root, locale.privacy), "utf8");
  const privacyContent = `<div class="article-layout"><aside class="toc"><strong>${locale.id === "en" ? "On this page" : labels.questions}</strong><a href="#data">${locale.id === "en" ? "What we access" : "Data"}</a><a href="#local">${locale.id === "en" ? "What stays on your device" : "Local processing"}</a><a href="#collect">${locale.id === "en" ? "What we do not collect" : "Collection"}</a><a href="#backup">${locale.id === "en" ? "Backups and sharing" : labels.backup}</a><a href="#contact">${locale.id === "en" ? "Contact us" : labels.support}</a></aside><article class="article"><h1>${locale.id === "en" ? "Privacy policy" : escapeHTML(privacy.split("\n")[0].replace(/^# /, ""))}</h1><p class="article-intro">${locale.id === "en" ? "ContactsDeduper processes your contacts on your device." : labels.intro}</p><p class="updated">${labels.updated} · August 2026</p><div class="callout"><strong>${locale.id === "en" ? "Local-first by design" : labels.careful}</strong><p>${locale.id === "en" ? "Your data stays on your device. We do not collect, store, or transmit your contacts." : labels.backupText}</p></div><div class="privacy-content">${markdownToHTML(privacy)}</div></article></div>`;
  write(path.join(dist, locale.id, "privacy", "index.html"), shell({ locale, page: "privacy", title: locale.id === "en" ? "Privacy policy" : "Privacy", description: labels.intro, content: privacyContent }));
  const terms = fs.readFileSync(path.join(root, locale.terms), "utf8");
  const termsContent = `<div class="article-layout"><aside class="toc"><strong>${labels.terms}</strong><a href="#license">${locale.id === "en" ? "Apple App Store terms" : "App Store"}</a><a href="#use">${locale.id === "en" ? "Acceptable use" : "Use"}</a><a href="#backup">${locale.id === "en" ? "Backups and contact data" : labels.backup}</a><a href="#warranty">${locale.id === "en" ? "Disclaimer" : "Disclaimer"}</a><a href="#liability">${locale.id === "en" ? "Limitation of liability" : "Liability"}</a><a href="#changes">${locale.id === "en" ? "Changes" : "Changes"}</a><a href="#contact">${locale.id === "en" ? "Contact" : labels.support}</a></aside><article class="article"><h1>${escapeHTML(terms.split("\n")[0].replace(/^# /, ""))}</h1><p class="article-intro">${labels.termsIntro}</p><p class="updated">${labels.updated} · August 2026</p><div class="callout"><strong>${locale.id === "en" ? "Please review before use" : labels.terms}</strong><p>${labels.termsIntro}</p></div><div class="privacy-content">${markdownToHTML(terms, ["license", "use", "backup", "warranty", "liability", "changes", "contact"])}</div></article></div>`;
  write(path.join(dist, locale.id, "terms", "index.html"), shell({ locale, page: "terms", title: labels.terms, description: labels.termsIntro, content: termsContent }));
}

write(path.join(dist, "index.html"), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=/en/support/"><link rel="canonical" href="/en/support/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><title>ContactsDeduper</title></head><body><p><a href="/en/support/">ContactsDeduper</a></p></body></html>`);
write(path.join(dist, "404.html"), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Page not found · ContactsDeduper</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"></head><body><main class="faq"><h1>Page not found</h1><p>The page you requested does not exist.</p><a class="button" href="/en/support/">Go to support</a></main></body></html>`);

function write(file, content) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content); }
